// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by script/generateDockerfileTemplates.ts
// Run 'bun run generate-dockerfiles' to regenerate

import type { FrameworkType } from './types.js';

/**
 * Embedded dockerfile templates for each supported framework
 * These are included in the compiled binary
 */
export const DOCKERFILE_TEMPLATES: Record<Exclude<FrameworkType, 'custom'>, string> = {
  'cargo': `# Rust Cargo Test Executor
FROM rust:latest

# Build arguments for repository configuration
ARG SOURCE_REPO
ARG SOURCE_COMMIT
ARG TEST_REPO
ARG TEST_COMMIT

# Install git
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /workspace

# Clone the source repository and checkout specific commit
RUN git clone \${SOURCE_REPO} source-repo && \\
    cd source-repo && \\
    git checkout \${SOURCE_COMMIT}

# Clone the test repository and checkout specific commit
RUN git clone \${TEST_REPO} test-repo && \\
    cd test-repo && \\
    git checkout \${TEST_COMMIT}

# Create merged project structure
# Start with test repo as base (has correct Cargo.toml and test structure)
RUN cp -r test-repo project

# Override src/ with solution from source repo
RUN rm -rf project/src && \\
    cp -r source-repo/src project/src

# Set working directory to the merged project
WORKDIR /workspace/project

# Build the project
RUN cargo build

# Run tests
CMD ["cargo", "test", "--", "--nocapture"]
`,
  'pytest-uv': `# Python UV + Pytest Test Executor
FROM python:3.11-slim

# Build arguments for repository configuration
ARG SOURCE_REPO
ARG SOURCE_COMMIT
ARG TEST_REPO
ARG TEST_COMMIT

# Install system dependencies
RUN apt-get update && apt-get install -y \\
    git \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.cargo/bin:\${PATH}"

# Set working directory
WORKDIR /workspace

# Clone the source repository and checkout specific commit
RUN git clone \${SOURCE_REPO} source-repo && \\
    cd source-repo && \\
    git checkout \${SOURCE_COMMIT}

# Clone the test repository and checkout specific commit
RUN git clone \${TEST_REPO} test-repo && \\
    cd test-repo && \\
    git checkout \${TEST_COMMIT}

# Create merged project structure
# Start with test repo as base (has correct pyproject.toml and test structure)
RUN cp -r test-repo project

# Override source files with solution from source repo
# Python projects may have src/ directory or .py files at root
RUN if [ -d source-repo/src ]; then \\
        rm -rf project/src && cp -r source-repo/src project/src; \\
    else \\
        find source-repo -maxdepth 1 -name "*.py" -exec cp {} project/ \\;; \\
    fi

# Set working directory to the merged project
WORKDIR /workspace/project

# Install dependencies with uv
RUN uv pip install --system -e .
RUN uv pip install --system pytest

# Run tests
CMD ["python", "-m", "pytest", "-v"]
`,
  'pytest-poetry': `# Python Poetry + Pytest Test Executor
FROM python:3.11-slim

# Build arguments for repository configuration
ARG SOURCE_REPO
ARG SOURCE_COMMIT
ARG TEST_REPO
ARG TEST_COMMIT

# Install system dependencies
RUN apt-get update && apt-get install -y \\
    git \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Install poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:\${PATH}"

# Set working directory
WORKDIR /workspace

# Clone the source repository and checkout specific commit
RUN git clone \${SOURCE_REPO} source-repo && \\
    cd source-repo && \\
    git checkout \${SOURCE_COMMIT}

# Clone the test repository and checkout specific commit
RUN git clone \${TEST_REPO} test-repo && \\
    cd test-repo && \\
    git checkout \${TEST_COMMIT}

# Create merged project structure
# Start with test repo as base (has correct pyproject.toml and test structure)
RUN cp -r test-repo project

# Override source files with solution from source repo
# Python projects may have src/ directory or .py files at root
RUN if [ -d source-repo/src ]; then \\
        rm -rf project/src && cp -r source-repo/src project/src; \\
    else \\
        find source-repo -maxdepth 1 -name "*.py" -exec cp {} project/ \\;; \\
    fi

# Set working directory to the merged project
WORKDIR /workspace/project

# Install dependencies with poetry
RUN poetry install --with dev

# Run tests
CMD ["poetry", "run", "pytest", "-v"]
`,
  'bun-test': `# Bun Test Executor
FROM oven/bun:latest

# Build arguments for repository configuration
ARG SOURCE_REPO
ARG SOURCE_COMMIT
ARG TEST_REPO
ARG TEST_COMMIT

# Install git
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /workspace

# Clone the source repository and checkout specific commit
RUN git clone \${SOURCE_REPO} source-repo && \\
    cd source-repo && \\
    git checkout \${SOURCE_COMMIT}

# Clone the test repository and checkout specific commit
RUN git clone \${TEST_REPO} test-repo && \\
    cd test-repo && \\
    git checkout \${TEST_COMMIT}

# Create merged project structure
# Start with test repo as base (has correct package.json and test structure)
RUN cp -r test-repo project

# Override src/ with solution from source repo
RUN rm -rf project/src && \\
    cp -r source-repo/src project/src

# Set working directory to the merged project
WORKDIR /workspace/project

# Install dependencies
RUN bun install

# Run tests
CMD ["bun", "test"]
`,
  'bun-jest': `# Bun with Jest Test Executor
FROM oven/bun:latest

# Build arguments for repository configuration
ARG SOURCE_REPO
ARG SOURCE_COMMIT
ARG TEST_REPO
ARG TEST_COMMIT

# Install git
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /workspace

# Clone the source repository and checkout specific commit
RUN git clone \${SOURCE_REPO} source-repo && \\
    cd source-repo && \\
    git checkout \${SOURCE_COMMIT}

# Clone the test repository and checkout specific commit
RUN git clone \${TEST_REPO} test-repo && \\
    cd test-repo && \\
    git checkout \${TEST_COMMIT}

# Create merged project structure
# Start with test repo as base (has correct package.json, jest config and test structure)
RUN cp -r test-repo project

# Override src/ with solution from source repo
RUN rm -rf project/src && \\
    cp -r source-repo/src project/src

# Set working directory to the merged project
WORKDIR /workspace/project

# Install dependencies
RUN bun install

# Run tests with Jest
CMD ["bun", "run", "jest"]
`,
  'node-jest': `# Node.js with Jest Test Executor
FROM node:20-slim

# Build arguments for repository configuration
ARG SOURCE_REPO
ARG SOURCE_COMMIT
ARG TEST_REPO
ARG TEST_COMMIT

# Install git
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /workspace

# Clone the source repository and checkout specific commit
RUN git clone \${SOURCE_REPO} source-repo && \\
    cd source-repo && \\
    git checkout \${SOURCE_COMMIT}

# Clone the test repository and checkout specific commit
RUN git clone \${TEST_REPO} test-repo && \\
    cd test-repo && \\
    git checkout \${TEST_COMMIT}

# Create merged project structure
# Start with test repo as base (has correct package.json, jest config and test structure)
RUN cp -r test-repo project

# Override src/ with solution from source repo
RUN rm -rf project/src && \\
    cp -r source-repo/src project/src

# Set working directory to the merged project
WORKDIR /workspace/project

# Install dependencies
RUN npm ci

# Run tests
CMD ["npm", "test"]
`,
  'pnpm-jest': `# PNPM with Jest Test Executor
FROM node:20-slim

# Build arguments for repository configuration
ARG SOURCE_REPO
ARG SOURCE_COMMIT
ARG TEST_REPO
ARG TEST_COMMIT

# Install git and pnpm
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN npm install -g pnpm

# Set working directory
WORKDIR /workspace

# Clone the source repository and checkout specific commit
RUN git clone \${SOURCE_REPO} source-repo && \\
    cd source-repo && \\
    git checkout \${SOURCE_COMMIT}

# Clone the test repository and checkout specific commit
RUN git clone \${TEST_REPO} test-repo && \\
    cd test-repo && \\
    git checkout \${TEST_COMMIT}

# Create merged project structure
# Start with test repo as base (has correct package.json, jest config and test structure)
RUN cp -r test-repo project

# Override src/ with solution from source repo
RUN rm -rf project/src && \\
    cp -r source-repo/src project/src

# Set working directory to the merged project
WORKDIR /workspace/project

# Install dependencies
RUN pnpm install --frozen-lockfile

# Run tests
CMD ["pnpm", "test"]
`,
};

/**
 * Get dockerfile content for a framework
 * @param framework The detected framework type
 * @returns The dockerfile content as a string
 */
export function getDockerfileContent(framework: Exclude<FrameworkType, 'custom'>): string {
  return DOCKERFILE_TEMPLATES[framework];
}
