/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function verifyIntent(
  testRepoUrl: string,
  testCommit: string,
  solutionRepoUrl: string,
  solutionCommit1: string,
  solutionCommit2: string,
  userIntent: string,
  apiKey: string,
  model?: string | undefined | null,
  baseUrl?: string | undefined | null,
): Promise<string>
