#!/usr/bin/env bun
/**
 * Script to generate dockerfileTemplates.ts from actual dockerfile files
 * This embeds the dockerfile content as string constants in the TypeScript code
 * so they are included in the compiled binary
 */

import { promises as fs } from 'fs';
import path from 'path';

const FRAMEWORKS_DIR = 'frameworks';
const OUTPUT_FILE = 'src/test-execution/dockerfileTemplates.ts';

const DOCKERFILE_MAP: Record<string, string> = {
  'cargo.dockerfile': 'cargo',
  'pytest_uv.dockerfile': 'pytest-uv',
  'pytest_poetry.dockerfile': 'pytest-poetry',
  'bun_test.dockerfile': 'bun-test',
  'bun_jest.dockerfile': 'bun-jest',
  'node_jest.dockerfile': 'node-jest',
  'pnpm_jest.dockerfile': 'pnpm-jest',
};

async function generateTemplates() {
  console.log('Generating dockerfile templates...');
  
  const templates: Record<string, string> = {};
  
  // Read all dockerfiles
  for (const [filename, framework] of Object.entries(DOCKERFILE_MAP)) {
    const filePath = path.join(FRAMEWORKS_DIR, filename);
    try {
      const content = await fs.readFile(filePath, 'utf-8');
      templates[framework] = content;
      console.log(`✓ Read ${filename}`);
    } catch (error) {
      console.error(`✗ Failed to read ${filename}:`, error);
      process.exit(1);
    }
  }
  
  // Generate TypeScript file
  const output = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by script/generateDockerfileTemplates.ts
// Run 'bun run generate-dockerfiles' to regenerate

import type { FrameworkType } from './types.js';

/**
 * Embedded dockerfile templates for each supported framework
 * These are included in the compiled binary
 */
export const DOCKERFILE_TEMPLATES: Record<Exclude<FrameworkType, 'custom'>, string> = {
${Object.entries(templates).map(([framework, content]) => {
  // Escape backticks and ${} in the content
  const escapedContent = content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
  return `  '${framework}': \`${escapedContent}\`,`;
}).join('\n')}
};

/**
 * Get dockerfile content for a framework
 * @param framework The detected framework type
 * @returns The dockerfile content as a string
 */
export function getDockerfileContent(framework: Exclude<FrameworkType, 'custom'>): string {
  return DOCKERFILE_TEMPLATES[framework];
}
`;
  
  await fs.writeFile(OUTPUT_FILE, output, 'utf-8');
  console.log(`\n✓ Generated ${OUTPUT_FILE}`);
  console.log('Dockerfile templates are now embedded in the code!');
}

generateTemplates().catch(error => {
  console.error('Failed to generate templates:', error);
  process.exit(1);
});
